[package]
name = "bakta-web-backend"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = "0.7.5"
chrono = { version = "0.4.38", features = ["serde"] }
dotenvy = "0.15.7"
lazy_static = "1.5.0"
rand = "0.8.5"
regex = "1.10.5"
reqsign = "0.16.0"
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tokio = { version = "1.38.1", features = ["full"] }
url = "2.5.2"
utoipa = { version = "4.2.3", features = ["uuid", "chrono"]}
utoipa-swagger-ui = { version = "7.1.0", features = ["axum"] }
uuid = { version = "1.10.0", features = ["v4", "serde"] }
